const API_BASE = "https://backend-ledger-0ra6.onrender.com";

const TOKEN_KEY = "auth_token";

const authHeaders = (): Record<string, string> => {
  const token = localStorage.getItem(TOKEN_KEY);
  return token
    ? { "Content-Type": "application/json", Authorization: `Bearer ${token}` }
    : { "Content-Type": "application/json" };
};

const handleUnauthorized = (res: Response) => {
  if (res.status === 401) {
    localStorage.removeItem(TOKEN_KEY);
    window.location.href = "/login";
    throw new Error("Session expired. Please login again.");
  }
};

export interface GameObject {
  name: string;
  logo: string;
  provider: string;
  provider_code: string;
  game_id: string | number;
  type: string;
  category: string;
}

export interface GameLaunchResponse {
  status: string;
  gameUrl: string;
  gameId?: string | number;
  type?: string;
  providerCode?: string;
  moveIn?: { amount: number; referenceId?: string | null };
}

export interface GameWithdrawResponse {
  status: string;
  msg?: string;
  moveOut: { amount: number; referenceId?: string | null };
  walletBalance?: number;
}


export const GAME_LIST: GameObject[] = [
   {
    name: "Fortune Gems 3",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/fortune-gem3.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 300,
    type: "SL",
    category: "slot",
  },
  {
    name: "Money Coming",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/money-coming.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 51,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Mouse",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/fortune-mouse%20(1).png",
    provider_code: "PG",
    provider: "pg",
    game_id: 68,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/fortune-gem2.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 223,
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/super-ace.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 49,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jackpot Joker",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/jackpot-joker.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 301,
    type: "SL",
    category: "slot",
  },
 
  {
    name: "Crazy777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/carzy-777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 35,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Rabbit",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/fortune-rabbit.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 1543462,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Ox",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/fortune-ox.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 98,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Tiger",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/fortune-tiger.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 126,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Hatch",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/dragon-hatch.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 57,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Bandito",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/wild-bandito.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 104,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mermaid Riches",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/mermaid-riches.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 102,
    type: "SL",
    category: "slot",
  },
  {
    name: "Leprechaun Riches",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/leprechaun-riches.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 60,
    type: "SL",
    category: "slot",
  },
  {
    name: "Captain's Bounty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/captains-bounty.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 54,
    type: "SL",
    category: "slot",
  },
  {
    name: "Queen of Bounty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/queen-bounty.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 84,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Bounty Showdown",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/wild-bounty-showdown.png",
    provider_code: "PG",
    provider: "pg",
    game_id: 135,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Tiger",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/dravstig.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 123,
    type: "CB",
    category: "casino",
  },
  {
    name: "Aviator",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/aviator.png",
    provider_code: "SPRIBE",
    provider: "spribe",
    game_id: "22_22001",
    type: "MG",
    category: "casino",
  },
  {
    name: "7Up 7Down",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/7up7downJLIjili.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 124,
    type: "CB",
    category: "casino",
  },
  {
    name: "Mines",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Mines5.png",
    provider_code: "SPRIBE",
    provider: "spribe",
    game_id: 229,
    type: "MG",
    category: "casino",
  },
  {
    name: "Tongits Go",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/TongitsGo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 199,
    type: "PK",
    category: "casino",
  },
  {
    name: "Big Small",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/BigSmall.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 524,
    type: "CB",
    category: "casino",
  },
  {
    name: "Ludo Quick",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/LudoQuick.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 163,
    type: "CB",
    category: "casino",
  },
  {
    name: "Color Prediction",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/ColorPrediction.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 204,
    type: "CB",
    category: "casino",
  },
  {
    name: "Plinko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Plinko.png",
    provider_code: "SPRIBE",
    provider: "spribe",
    game_id: 242,
    type: "MG",
    category: "casino",
  },
  {
    name: "Chicken Dash",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/chicken%20dash.png",
    provider_code: "SPRIBE",
    provider: "spribe",
    game_id: 690,
    type: "MG",
    category: "casino",
  },
 
  {
    name: "Black Jack",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/black%20jack.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 219,
    type: "CB",
    category: "casino",
  },
  
  {
    name: "Mines 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Mines2.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9021",
    type: "MG",
    category: "casino",
  },
  {
    name: "Mines",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Mines3.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9014",
    type: "MG",
    category: "casino",
  },
  {
    name: "Dice",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Dice123.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9019",
    type: "MG",
    category: "casino",
  },
  {
    name: "Hilo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Hilo123.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9017",
    type: "MG",
    category: "casino",
  },
  {
    name: "Mole Crash",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/MoleCrash.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9020",
    type: "MG",
    category: "casino",
  },
  {
    name: "Dragon Tiger Joker Bonus",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/DragonTigerJokerBonus.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "18_18026",
    type: "CB",
    category: "casino",
  },
  {
    name: "Goal",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Goal123.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9016",
    type: "MG",
    category: "casino",
  },
  {
    name: "Lucky Colour Game",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/LuckyColorGame.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9010",
    type: "CB",
    category: "casino",
  },
  
  {
    name: "Roma X",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/RomaX.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 102,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jackpot Joker",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/JackpotJoker.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 605,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy 777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Crazy777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 35,
    type: "SL",
    category: "slot",
  },
  {
    name: "Gold Rush",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/GoldRushjili.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 137,
    type: "SL",
    category: "slot",
  },
  {
    name: "Sic Bo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/SicBojili.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 125,
    type: "CB",
    category: "casino",
  },
  {
    name: "Win Drop",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/WinDrop.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 179,
    type: "MG",
    category: "casino",
  },
  
  {
    name: "Color Game",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/ColorGamejili.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 197,
    type: "CB",
    category: "casino",
  },
  {
    name: "Golden Temple",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/GoldenTemple.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 191,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jhandi Mundi",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/jili0811JhandiMunda%20(1).png",
    provider_code: "JE",
    provider: "jili",
    game_id: 397,
    type: "CB",
    category: "casino",
  },
  {
    name: "Neko Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/NekoFortune.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 145,
    type: "SL",
    category: "slot",
  },
  {
    name: "Keno",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Kenojili.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 241,
    type: "LK",
    category: "casino",
  },
  {
    name: "Mines Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/MinesGold.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 254,
    type: "MG",
    category: "casino",
  },
  {
    name: "Limbo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Limbo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 235,
    type: "MG",
    category: "casino",
  },
  {
    name: "Go Rush",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/GoRush%20(1).png",
    provider_code: "JE",
    provider: "jili",
    game_id: 224,
    type: "MG",
    category: "casino",
  },
  {
    name: "Tower",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Tower.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 232,
    type: "MG",
    category: "casino",
  },
  {
    name: "Hilo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/HILOjili.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 233,
    type: "MG",
    category: "casino",
  },
  {
    name: "Baccarat",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Baccaratjili.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 152,
    type: "CB",
    category: "casino",
  },
  {
    name: "Dragon Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/DragonTreasure.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 46,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mines Grand",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/jili0811MinesGrand.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 546,
    type: "MG",
    category: "casino",
  },
  {
    name: "Cricket War",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/jili0811CricketWar.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 473,
    type: "MG",
    category: "casino",
  },
  {
    name: "Penalty Kick",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/jili0811PenaltyKick.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 419,
    type: "MG",
    category: "casino",
  },
  {
    name: "Money Coming 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/jili0811MoneyComing2.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 543,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/jili0811GoldenTreasure.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 554,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Queen",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/GoldenQueen.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 58,
    type: "SL",
    category: "slot",
  },
  {
    name: "777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 27,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Coming",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 91,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Bank",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/GoldenBank.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 45,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mega Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/MegaAce.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 134,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/FortuneGems.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 109,
    type: "SL",
    category: "slot",
  },
  {
    name: "Happy Taxi",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/HappyTaxi.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 116,
    type: "SL",
    category: "slot",
  },
  {
    name: "Andar Bahar",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/AndarBahar.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 97,
    type: "CB",
    category: "casino",
  },

  {
    name: "Fortune Zombie",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/jili0811FORTUNEZOMBIE.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 531,
    type: "SL",
    category: "fish",
  },
  {
    name: "Royal Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/RoyalFishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 1,
    type: "FH",
    category: "fish",
  },
  {
    name: "Ocean King Jackpot",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/OceanKingJackpot.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 289,
    type: "FH",
    category: "kish",
  },
  {
    name: "Bombing Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/BombingFishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 20,
    type: "FH",
    category: "fish",
  },
  {
    name: "Dinosaur Tycoon",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/DinosaurTycoon.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 42,
    type: "FH",
    category: "casino",
  },
  {
    name: "Dinosaur Tycoon 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/DinosaurTycoonII.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 212,
    type: "FH",
    category: "casino",
  },
  {
    name: "Jackpot Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/JackpotFishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 32,
    type: "FH",
    category: "fish",
  },
  {
    name: "Happy Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/HappyFishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 82,
    type: "FH",
    category: "fish",
  },
  {
    name: "Mega Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/MegaFishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 74,
    type: "FH",
    category: "fish",
  },
  {
    name: "Fishing Disco",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/FishingDisco.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7007",
    type: "FH",
    category: "fish",
  },
  {
    name: "Dragon Master",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/DragonMaster.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7006",
    type: "SL",
    category: "fish",
  },


  {
    name: "Fishing Yilufa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/FishingYilufa.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7005",
    type: "FH",
    category: "fish",
  },
  {
    name: "Cai Shen Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/CaiShenFishing.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7003",
    type: "FH",
    category: "fish",
  },
  {
    name: "Shade Dragons Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/ShadeDragonsFishing.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7004",
    type: "FH",
    category: "fish",
  },
  
  {
  name: "1Tap Mines",
  logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/01-1x1-1tapmines-thumb.png",
  provider_code: "TU",
  provider: "turbo",
  game_id: "1tapmines",
  type: "MG",
  category: "casino",
},
{
    name: "Vortex 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/06-vortex2-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortex2",
    type: "SL",
    category: "slot",
  },
  {
    name: "Vortex Safari",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/06-vortexsafari-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortexsafari",
    type: "SL",
    category: "slot",
  },
  {
    name: "Balloon Doggo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/07-balloondoggo-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "balloondoggo",
    type: "MG",
    category: "casino",
  },
  {
    name: "Vortex Halloween",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/07-vortexhalloween-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortexhalloween",
    type: "SL",
    category: "slot",
  },
  {
    name: "Vortex Powerplay",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/07-vortexpowerplay-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortexpowerplay",
    type: "SL",
    category: "slot",
  },
  {
    name: "Chicken Route",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/06-chickenroute-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "chickenroute",
    type: "MG",
    category: "casino",
  },
  {
    name: "CrashX",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/02-1x1-crash-thumb.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "crash",
    type: "MG",
    category: "casino",
  },
  {
    name: "Towers",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Towers_4_3.jpg",
    provider_code: "TU",
    provider: "turbo",
    game_id: "towers",
    type: "MG",
    category: "casino",
  },
  {
    name: "Aero",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Aero_thumb_1x1%20(1).png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "aero",
    type: "MG",
    category: "casino",
  },
  {
    name: "Limbo Rider",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/LimboRider_1_1.jpg",
    provider_code: "TU",
    provider: "turbo",
    game_id: "limbo",
    type: "MG",
    category: "casino",
  },
  {
    name: "Hamsta",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Hamsta_1_1_bright.jpg",
    provider_code: "TU",
    provider: "turbo",
    game_id: "hamsta",
    type: "MG",
    category: "casino",
  },
  {
    name: "Dice Twice",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Dice_1_1%20(1).jpeg",
    provider_code: "TU",
    provider: "turbo",
    game_id: "dice",
    type: "MG",
    category: "casino",
  },
  {
    name: "Turbo Mines",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Mines1_1.jpeg",
    provider_code: "TU",
    provider: "turbo",
    game_id: "turbomines",
    type: "MG",
    category: "casino",
  },
  {
    name: "Mysteco",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/06-mysteco-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "mysteco",
    type: "MG",
    category: "casino",
  },
  {
  name: "Turbo Mines",
  logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Mines1_1.jpeg",
  provider_code: "TU",
  provider: "turbo",
  game_id: "turbomines",
  type: "MG",
  category: "casino",
},
 {
    name: "Lucky Neko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/lucky%20neko.avif",
    provider_code: "PG",
    provider: "pg",
    game_id: 89,
    type: "SL",
    category: "slot",
  },
  {
    name: "Treasures of Aztec",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/treasure%20of%20aztec.avif",
    provider_code: "PG",
    provider: "pg",
    game_id: 87,
    type: "SL",
    category: "slot",
  },
  {
    name: "Anubis Wrath",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/anubis%20wrath.avif",
    provider_code: "PG",
    provider: "pg",
    game_id: 1623475,
    type: "SL",
    category: "slot",
  },
   {
    name: "Trump Card",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/trumpcard.avif",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14077",
    type: "SL",
    category: "slot",
  },
  {
    name: "Bull Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/bull%20treasure.avif",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14094",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Neko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/fortuneneko.avif",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14075",
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Niubi Deluxe",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/superniubideluxe.avif",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14045",
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Color Game",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/LuckyColorGame.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9010",
    type: "CB",
    category: "casino",
  },
  {
    name: "Dice",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Dice12.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9019",
    type: "MG",
    category: "casino",
  },
  {
    name: "Hilo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Hilo.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9017",
    type: "MG",
    category: "casino",
  },
  {
    name: "Goal",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Goal.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9016",
    type: "MG",
    category: "casino",
  },
  {
    name: "Plinko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/Plinko.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9018",
    type: "MG",
    category: "casino",
  },
  {
  name: "Vortex",
  logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/14-Thumb-logo%20-%201x1.png",
  provider_code: "TU",
  provider: "turbo",
  game_id: "vortex",
  type: "SL",
  category: "casino",
},
{
  name: "Turbo Plinko",
  logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/1x1.png",
  provider_code: "TU",
  provider: "turbo",
  game_id: "turboplinko",
  type: "MG",
  category: "casino",
},
];

export interface GameBalanceResponse {
  status: string;
  walletBalance: number;
  gameBalance: Record<string, number>;
  totalBalance: number;
}

export const gameService = {
  async getBalance(): Promise<GameBalanceResponse> {
    const res = await fetch(`${API_BASE}/api/game/balance`, {
      headers: authHeaders(),
    });
    handleUnauthorized(res);
    const data = await res.json();
    if (!res.ok || data.status !== "success") {
      throw new Error(data.msg || "Failed to fetch balances");
    }
    return data;
  },

  async launch(game: GameObject): Promise<GameLaunchResponse> {
    const params = new URLSearchParams({
      g_id: String(game.game_id),
      p_code: game.provider_code,
      type: game.type,
      lang: "en-US",
      html5: "1",
    });
    const res = await fetch(`${API_BASE}/api/game/launch?${params}`, {
      headers: authHeaders(),
    });
    handleUnauthorized(res);
    const rawData = await res.json();
    const data = Array.isArray(rawData) ? rawData[0] : rawData;
    if (!res.ok || data.status !== "success") {
      throw new Error(data.msg || data.error || data.message || "Game launch failed");
    }
    return data;
  },

  async withdraw(providerCode: string): Promise<GameWithdrawResponse> {
    const res = await fetch(`${API_BASE}/api/game/withdraw`, {
      method: "POST",
      headers: authHeaders(),
      body: JSON.stringify({ p_code: providerCode }),
    });
    handleUnauthorized(res);
    const data = await res.json();
    if (!res.ok || (data.status !== "success" && !data.moveOut)) {
      throw new Error(data.msg || data.error || data.message || "Withdraw failed");
    }
    return data;
  },
};
