export const JD_GAMES = [
  {
    name: "Beer Tycoon",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBbeertyccon.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9004",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Big Three Dragons",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBbigthreedragons.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14063",
    type: "SL",
    category: "slot",
  },
  {
    name: "Billionaire",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBbillonaire.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14006",
    type: "SL",
    category: "slot",
  },
  {
    name: "Birds And Animals",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBbirdsandanimls.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9003",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Birds Party",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBbirdsparty.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14033",
    type: "SL",
    category: "slot",
  },
  {
    name: "Blossom Of Wealth",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBblossomofwealth.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14065",
    type: "SL",
    category: "slot",
  },
  {
    name: "Book Of Mystery",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBbookofmystery.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14070",
    type: "SL",
    category: "slot",
  },
  {
    name: "Bull Treasure X-Huge",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBbulltreasure.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14094",
    type: "SL",
    category: "slot",
  },
  {
    name: "Cai Shen Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBcaishen%20fishing.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7003",
    type: "FH",
    category: "fish",
  },
  {
    name: "Caishen Coming",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBcaishencoming.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14084",
    type: "SL",
    category: "slot",
  },
  {
    name: "Caishen Party",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBcaishenparty.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9011",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Crazy King Kong",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBcrazykingkong.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9008",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Dice",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/SPRIBEgamelogo/SPRIBEdice.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9019",
    type: "MG",
    category: "casino",
  },
  {
    name: "Dragon",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBdragon.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14010",
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBdragonfishing.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7001",
    type: "FH",
    category: "fish",
  },
  {
    name: "Dragon Fishing II",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBdragonfishing2.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7002",
    type: "FH",
    category: "fish",
  },
  {
    name: "Dragon Master",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBdragonmaster.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7006",
    type: "FH",
    category: "fish",
  },
  {
    name: "Dragon of Demons",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBdragonofdemons.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7010",
    type: "FH",
    category: "fish",
  },
  {
    name: "Dragon Soar - Hyper Wild",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBdragonsoarhyperwild.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14092",
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragons Gate",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBdragonsgate.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14051",
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragons World",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBdragonsworld.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14035",
    type: "SL",
    category: "slot",
  },
  {
    name: "Elemental Link Fire",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBelementallinkfire.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14080",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fishin' Fever X-Huge",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfishin%20feverxhuge.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14097",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fishing Disco",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfishingdisco.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7007",
    type: "FH",
    category: "fish",
  },
  {
    name: "Fishing Yilufa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfishingyilufa.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7005",
    type: "FH",
    category: "fish",
  },
  {
    name: "Flirting Scholar Tang",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBflirtingscholartang.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8002",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Horse",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfortunehorse.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8050",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Jewel",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfrotunejewel.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14095",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Neko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfortuneneko.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14075",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfortunetreasure.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14039",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fruity Bonanza",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfruitybonanza.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14085",
    type: "SL",
    category: "slot",
  },
  {
    name: "Funky King Kong",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfunkykingkong.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14044",
    type: "SL",
    category: "slot",
  },
  {
    name: "Glamorous Girl",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBglamorousgirl.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14067",
    type: "SL",
    category: "slot",
  },
  {
    name: "Go Lai Fu",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBgolaifu.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14034",
    type: "SL",
    category: "slot",
  },
  {
    name: "Goal",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/SPRIBEgamelogo/SPRIBEgoal.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9016",
    type: "MG",
    category: "casino",
  },
  {
    name: "Golden Disco",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBgoldendisco.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14043",
    type: "SL",
    category: "slot",
  },
  {
    name: "Happy New Year",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBhapplynewyear.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9002",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Hilo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/SPRIBEgamelogo/SPRIBEhilo.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9017",
    type: "MG",
    category: "casino",
  },
  {
    name: "Huaguoshan Legends",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBhuacuoshanlegends.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9006",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Jogo Do Bicho",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBjogodobicho.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9012",
    type: "AR",
    category: "arcade",
  },
  {
    name: "King Of Football",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBkingoffootball.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9009",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Kingsman",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBkingsman.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14016",
    type: "SL",
    category: "slot",
  },
  {
    name: "Koi Trio",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBkoitrio.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14100",
    type: "SL",
    category: "slot",
  },
  {
    name: "Lantern Wealth",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBlanternwealth.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14060",
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Color Game",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBluckycolorgame.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9010",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Lucky Diamond",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBluckydaimond.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14054",
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Dragons",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBluckydragons.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8001",
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Seven",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBluckyseven.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14027",
    type: "SL",
    category: "slot",
  },
  {
    name: "Magic Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBmagicace.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14088",
    type: "SL",
    category: "slot",
  },
  {
    name: "Magic Ace WILD LOCK",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBmagicacewildlock.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14093",
    type: "SL",
    category: "slot",
  },
  {
    name: "Mahjong",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBmahjong.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8022",
    type: "SL",
    category: "slot",
  },
  {
    name: "Mayagold Crazy",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBmayagoldcrazy.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14061",
    type: "SL",
    category: "slot",
  },
  {
    name: "Miner Babe",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBminerbabe.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14046",
    type: "SL",
    category: "slot",
  },
  {
    name: "Mjolnir",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBmjolnir.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14041",
    type: "SL",
    category: "slot",
  },
  {
    name: "Moneybags Man",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBmonetbagsman.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14047",
    type: "SL",
    category: "slot",
  },
  {
    name: "Moneybags Man 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBmoneybagsman2.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14079",
    type: "SL",
    category: "slot",
  },
  {
    name: "New Year",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBnewyear.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8017",
    type: "SL",
    category: "slot",
  },
  {
    name: "Olympian Temple",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBolymplantemple.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8023",
    type: "SL",
    category: "slot",
  },
  {
    name: "Olympig",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBolympig.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_6001",
    type: "SL",
    category: "slot",
  },
  {
    name: "Open Sesame",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBopensesame.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8020",
    type: "SL",
    category: "slot",
  },
  {
    name: "Open Sesame II",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBopensesame2.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8048",
    type: "SL",
    category: "slot",
  },
  {
    name: "Open Sesame Mega",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBopensesamemega.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14086",
    type: "SL",
    category: "slot",
  },
  {
    name: "Orient Animals",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBorientanimals.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14029",
    type: "SL",
    category: "slot",
  },
  {
    name: "Piggy Bank",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBpiggybank.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14091",
    type: "SL",
    category: "slot",
  },
  {
    name: "Plinko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBplinko.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9018",
    type: "AR",
    category: "arcade",
  },
  {
    name: "Pop Pop Candy",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBpoppopcandy.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14087",
    type: "SL",
    category: "slot",
  },
  {
    name: "Prosperity Tiger",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBprosperitytiger.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14068",
    type: "SL",
    category: "slot",
  },
  {
    name: "Ragnarok : Thor VS Loki",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBragnarokthorvsloki.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14101",
    type: "SL",
    category: "slot",
  },
  {
    name: "Rooster In Love",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBroosterinlove.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_15001",
    type: "SL",
    category: "slot",
  },
  {
    name: "Spindrift 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBspindrift2.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14053",
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Niubi",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBsuperniubi.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14036",
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Niubi Deluxe",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBsuperniubideluxe.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14045",
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Super Fruit",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBsuperfruit.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9007",
    type: "AR",
    category: "arcade",
  },
  {
    name: "The Llama Adventure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBthellamaadventure.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8005",
    type: "SL",
    category: "slot",
  },
  {
    name: "Treasure Bowl X-Huge",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBtreasurebowl.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14042",
    type: "SL",
    category: "slot",
  },
  {
    name: "Triple King Kong",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBtriplekingkong.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14030",
    type: "SL",
    category: "slot",
  },
  {
    name: "Trump Card",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBtrumpcard.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14077",
    type: "SL",
    category: "slot",
  },
  {
    name: "Winning Mask",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBwinningmask.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8003",
    type: "SL",
    category: "slot",
  },
  {
    name: "Winning Mask II",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBwinningmask2.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8047",
    type: "SL",
    category: "slot",
  },
  {
    name: "Wonder Elephant",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBwonderelephant.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14058",
    type: "SL",
    category: "slot",
  },
  {
    name: "Xi Yang Yang",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDByangyang.jpg",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_8051",
    type: "SL",
    category: "slot",
  },
];
