export const JD_GAMES = [
  {
    name: "Fishing Disco",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/FishingDisco.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7007",
    type: "FH",
    category: "fish",
  },
  {
    name: "Dragon Master",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/DragonMaster.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7006",
    type: "SL",
    category: "fish",
  },
  {
    name: "Fishing Yilufa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/FishingYilufa.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7005",
    type: "FH",
    category: "fish",
  },
  {
    name: "Cai Shen Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/CaiShenFishing.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7003",
    type: "FH",
    category: "fish",
  },
  {
    name: "Shade Dragons Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/ShadeDragonsFishing.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "7_7004",
    type: "FH",
    category: "fish",
  },
  {
    name: "Trump Card",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBtrumpcard.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14077",
    type: "SL",
    category: "slot",
  },
  {
    name: "Bull Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBbulltreasure.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14094",
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Neko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBfortuneneko.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14075",
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Niubi Deluxe",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBsuperniubideluxe.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "0_14045",
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Color Game",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/JDBgamelogo/JDBluckycolorgame.png",
    provider_code: "JD",
    provider: "jdb",
    game_id: "9_9010",
    type: "CB",
    category: "casino",
  },
  {
    name: "Dice",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/SPRIBEgamelogo/SPRIBEdice.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9019",
    type: "MG",
    category: "casino",
  },
  {
    name: "Hilo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/SPRIBEgamelogo/SPRIBEhilo.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9017",
    type: "MG",
    category: "casino",
  },
  {
    name: "Goal",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/SPRIBEgamelogo/SPRIBEgoal.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9016",
    type: "MG",
    category: "casino",
  },
  {
    name: "Plinko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/SPRIBEgamelogo/SPRIBEplinko.png",
    provider_code: "JD",
    provider: "spribe",
    game_id: "9_9018",
    type: "MG",
    category: "casino",
  },
];
