export const JE_GAMES = [
  {
    name: "3 Coin Treasures",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/J3cointreasures.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 399,
    type: "SL",
    category: "slot",
  },
  {
    name: "777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/J777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 27,
    type: "SL",
    category: "slot",
  },
  {
    name: "Agent Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jagentace.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 115,
    type: "SL",
    category: "slot",
  },
  {
    name: "Alibaba",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jalibaba.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 110,
    type: "SL",
    category: "slot",
  },
  {
    name: "All Star Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jallstarfishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 119,
    type: "SL",
    category: "slot",
  },
  {
    name: "Arena Fighter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jarenafiger.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 228,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ascent Charge Buffalo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jasentchargebuffalo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 259,
    type: "SL",
    category: "slot",
  },
  {
    name: "Aztec Priestess",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jaztecpriestess.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 209,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bangla Beauty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbanglabeauty.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 238,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bao Boon Chin",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbaogoonchin.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 36,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bingo Carnaval",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbingocarnaval.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 148,
    type: "SL",
    category: "slot",
  },
  {
    name: "Blackjack",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jblackjack.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 219,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bombing Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbombingishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 20,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bone Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbonefortune.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 126,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bonus Hunter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbonushunter.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 142,
    type: "SL",
    category: "slot",
  },
  {
    name: "Book of Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbookofgold.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 87,
    type: "SL",
    category: "slot",
  },
  {
    name: "Boom Legend",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jboomlegend.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 71,
    type: "SL",
    category: "slot",
  },
  {
    name: "Boxing King",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jboxingking.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 77,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bubble Beauty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbubblebeauty.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 30,
    type: "SL",
    category: "slot",
  },
  {
    name: "Candy Baby",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcandybaby.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 23,
    type: "SL",
    category: "slot",
  },
  {
    name: "Charge Buffalo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jchargebuffalo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 47,
    type: "SL",
    category: "slot",
  },
  {
    name: "Chin Shi Huang",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jchinshi.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 2,
    type: "SL",
    category: "slot",
  },
  {
    name: "Color Game",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcolorgame.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 197,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy 777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazy777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 35,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fa Fa Fa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfafafa.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 21,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fengshen",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfengshen.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 38,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunegems.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 109,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunegems2%20(1).png",
    provider_code: "JE",
    provider: "jili",
    game_id: 223,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdragontreasure.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 46,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdragonfortune.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 60,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Dinosaur Tycoon II",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdinosaurtycoon2.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 212,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Dinosaur Tycoon",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdinosaurtycoon.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 42,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Devil Fire 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdevilfire2.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 258,
    type: "SL",
    category: "slot",
  },
  {
    name: "Devil Fire",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdevilfire.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 193,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dabanggg",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdabanggg.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 239,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy Pusher",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazypusher.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 153,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy Hunter 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazyhunter2.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 420,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy Hunter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazyhunter.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 92,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy FaFaFa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazyfafafa.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 40,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Tree",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunetree.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 6,
    type: "SL",
    category: "slot",
  },
  {
    name: "FortunePig",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunepig.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 33,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Monkey",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunemonkey.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 303,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems 3",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunegems3.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 300,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Empire",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldenempire.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 103,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Bank",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldenbank.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 45,
    type: "SL",
    category: "slot",
  },
  {
    name: "God Of Martial",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgodofmartial.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 4,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jungle King",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfungleking.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 16,
    type: "SL",
    category: "slot",
  },
  {
    name: "Happy Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jhappyfishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 82,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Gold Rush",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldrush.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 137,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Temple",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldentemple.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 191,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Queen",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldenqueen.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 58,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Joker",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldenjoker.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 183,
    type: "SL",
    category: "slot",
  },
  {
    name: "Zeus",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jjeus.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 252,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jackpot Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jjackpotfishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 32,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Elf Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jirichbingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 172,
    type: "SL",
    category: "slot",
  },
  {
    name: "Hot Chilli",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jhotchilli.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 5,
    type: "SL",
    category: "slot",
  },
  {
    name: "Happy Taxi",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jhappytaxi.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 116,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Goldbricks",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jluckygoldbricks.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 48,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Coming",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jluckycoming.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 91,
    type: "SL",
    category: "slot",
  },
  {
    name: "Legacy of Egypt",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jlegacyofegypt.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 180,
    type: "SL",
    category: "slot",
  },
  {
    name: "King Arthur",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jkingarthur.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 214,
    type: "SL",
    category: "slot",
  },
  {
    name: "JILI CAISHEN",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jjilicaishen.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 144,
    type: "SL",
    category: "slot",
  },
];
