export const JE_GAMES = [
  {
    name: "3 Coin Treasures",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/J3cointreasures.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 399,
    type: "SL",
    category: "slot",
  },
  {
    name: "777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/J777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 27,
    type: "SL",
    category: "slot",
  },
  {
    name: "Agent Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jagentace.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 115,
    type: "SL",
    category: "slot",
  },
  {
    name: "Alibaba",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jalibaba.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 110,
    type: "SL",
    category: "slot",
  },
  {
    name: "All Star Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jallstarfishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 119,
    type: "SL",
    category: "slot",
  },
  {
    name: "Arena Fighter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jarenafiger.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 228,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ascent Charge Buffalo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jasentchargebuffalo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 259,
    type: "SL",
    category: "slot",
  },
  {
    name: "Aztec Priestess",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jaztecpriestess.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 209,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bangla Beauty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbanglabeauty.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 238,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bao Boon Chin",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbaogoonchin.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 36,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bingo Carnaval",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbingocarnaval.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 148,
    type: "SL",
    category: "slot",
  },
  {
    name: "Blackjack",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jblackjack.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 219,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bombing Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbombingishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 20,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bone Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbonefortune.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 126,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bonus Hunter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbonushunter.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 142,
    type: "SL",
    category: "slot",
  },
  {
    name: "Book of Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbookofgold.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 87,
    type: "SL",
    category: "slot",
  },
  {
    name: "Boom Legend",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jboomlegend.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 71,
    type: "SL",
    category: "slot",
  },
  {
    name: "Boxing King",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jboxingking.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 77,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bubble Beauty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbubblebeauty.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 30,
    type: "SL",
    category: "slot",
  },
  {
    name: "Candy Baby",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcandybaby.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 23,
    type: "SL",
    category: "slot",
  },
  {
    name: "Charge Buffalo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jchargebuffalo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 47,
    type: "SL",
    category: "slot",
  },
  {
    name: "Chin Shi Huang",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jchinshi.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 2,
    type: "SL",
    category: "slot",
  },
  {
    name: "Color Game",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcolorgame.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 197,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy 777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazy777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 35,
    type: "SL",
    category: "slot",
  },
];
