export const JE_GAMES = [
  {
    name: "Money Coming",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jmoneycoming.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 51,
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jsuperace.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 49,
    type: "SL",
    category: "slot",
  },
  {
    name: "Boxing King",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jboxingking.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 77,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunegems.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 109,
    type: "SL",
    category: "slot",
  },
  {
    name: "Charge Buffalo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jchargebuffalo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 47,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Empire",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldenempire.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 103,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Coming",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jluckycoming.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 91,
    type: "SL",
    category: "slot",
  },
  {
    name: "777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/J777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 27,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy 777",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazy777.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 35,
    type: "SL",
    category: "slot",
  },
  {
    name: "FortunePig",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunepig.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 33,
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Ace Deluxe",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jsuperacedeluxe.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 403,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunegems2%20(1).png",
    provider_code: "JE",
    provider: "jili",
    game_id: 223,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Goldbricks",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jluckygoldbricks.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 48,
    type: "SL",
    category: "slot",
  },
  {
    name: "TWIN WINS",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jtwinwins.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 106,
    type: "SL",
    category: "slot",
  },
  {
    name: "Candy Baby",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcandybaby.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 23,
    type: "SL",
    category: "slot",
  },
  {
    name: "Pharaoh Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jpharaohtreasure.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 85,
    type: "SL",
    category: "slot",
  },
  {
    name: "Agent Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jagentace.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 115,
    type: "SL",
    category: "slot",
  },
  {
    name: "3 Coin Treasures",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/J3cointreasures.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 399,
    type: "SL",
    category: "slot",
  },
  {
    name: "Alibaba",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jalibaba.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 110,
    type: "SL",
    category: "slot",
  },
  {
    name: "Arena Fighter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jarenafiger.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 228,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ascent Charge Buffalo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jasentchargebuffalo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 259,
    type: "SL",
    category: "slot",
  },
  {
    name: "Aztec Priestess",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jaztecpriestess.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 209,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bangla Beauty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbanglabeauty.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 238,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bao Boon Chin",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbaogoonchin.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 36,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bone Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbonefortune.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 126,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bonus Hunter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbonushunter.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 142,
    type: "SL",
    category: "slot",
  },
  {
    name: "Book of Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbookofgold.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 87,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bubble Beauty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbubblebeauty.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 30,
    type: "SL",
    category: "slot",
  },
  {
    name: "Chin Shi Huang",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jchinshi.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 2,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy FaFaFa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazyfafafa.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 40,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy Hunter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazyhunter.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 92,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy Hunter 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazyhunter2.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 420,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crazy Pusher",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcrazypusher.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 153,
    type: "SL",
    category: "slot",
  },
  {
    name: "Cricket King 18",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jcricketking18.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 225,
    type: "SL",
    category: "slot",
  },
  {
    name: "Cricket Sah 75",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jcricketsah75.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 230,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dabanggg",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdabanggg.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 239,
    type: "SL",
    category: "slot",
  },
  {
    name: "Devil Fire",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdevilfire.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 193,
    type: "SL",
    category: "slot",
  },
  {
    name: "Devil Fire 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdevilfire2.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 258,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdragontreasure.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 46,
    type: "OT",
    category: "arcade",
  },
  {
    name: "Elf Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jirichbingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 172,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fa Fa Fa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfafafa.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 21,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fengshen",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfengshen.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 38,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems 3",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunegems3.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 300,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Monkey",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunemonkey.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 303,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Tree",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunetree.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 6,
    type: "SL",
    category: "slot",
  },
  {
    name: "God Of Martial",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgodofmartial.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 4,
    type: "SL",
    category: "slot",
  },
  {
    name: "Gold Rush",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldrush.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 137,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Bank",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldenbank.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 45,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Joker",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldenjoker.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 183,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Queen",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldenqueen.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 58,
    type: "SL",
    category: "slot",
  },
  {
    name: "Golden Temple",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jgoldentemple.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 191,
    type: "SL",
    category: "slot",
  },
  {
    name: "Happy Taxi",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jhappytaxi.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 116,
    type: "SL",
    category: "slot",
  },
  {
    name: "Hot Chilli",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jhotchilli.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 5,
    type: "SL",
    category: "slot",
  },
  {
    name: "JILI CAISHEN",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jjilicaishen.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 144,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jungle King",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfungleking.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 16,
    type: "SL",
    category: "slot",
  },
  {
    name: "King Arthur",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jkingarthur.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 214,
    type: "SL",
    category: "slot",
  },
  {
    name: "Legacy of Egypt",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jlegacyofegypt.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 180,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Ball",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jluckynumber.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 13,
    type: "SL",
    category: "slot",
  },
  {
    name: "Magic Lamp",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jmagiclamp.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 108,
    type: "SL",
    category: "slot",
  },
  {
    name: "Master Tiger",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jmastertiger.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 176,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mayan Empire",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jmayanempire.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 135,
    type: "SL",
    category: "slot",
  },
  {
    name: "Medusa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jmedusa.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 101,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mega Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jmegaace.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 134,
    type: "SL",
    category: "slot",
  },
  {
    name: "Neko Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jnekofortune.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 145,
    type: "SL",
    category: "slot",
  },
  {
    name: "Party Ape",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jmonkeyparty.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 586,
    type: "SL",
    category: "slot",
  },
  {
    name: "Pirate Queen",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jpireatqueen.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 164,
    type: "SL",
    category: "slot",
  },
  {
    name: "Potion Wizard",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jpotionwizard.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 299,
    type: "SL",
    category: "slot",
  },
  {
    name: "Roma X",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jromax.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 102,
    type: "SL",
    category: "slot",
  },
  {
    name: "Samba",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jsambay.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 136,
    type: "SL",
    category: "slot",
  },
  {
    name: "Secret Treasure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jsecrettreasure.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 78,
    type: "SL",
    category: "slot",
  },
  {
    name: "Shanghai Beauty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jshanghaibeauty.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 17,
    type: "SL",
    category: "slot",
  },
  {
    name: "Sin City",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jsincity.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 171,
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Rich",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jsuperrion.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 100,
    type: "SL",
    category: "slot",
  },
  {
    name: "Sweet Land",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jsweetland.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 198,
    type: "SL",
    category: "slot",
  },
  {
    name: "The Pig House",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jthepighouse.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 263,
    type: "SL",
    category: "slot",
  },
  {
    name: "Thor X",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jthorx.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 130,
    type: "SL",
    category: "slot",
  },
  {
    name: "Trial of Phoenix",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jtrialofphoenix.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 208,
    type: "SL",
    category: "slot",
  },
  {
    name: "War Of Dragons",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jwarofdragons.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 9,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Ace",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jwildace.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 181,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Racer",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jwildracer.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 166,
    type: "SL",
    category: "slot",
  },
  {
    name: "World Cup",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jworldcup.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 146,
    type: "SL",
    category: "slot",
  },
  {
    name: "XiYangYang",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jxiyangyang.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 43,
    type: "SL",
    category: "slot",
  },
  {
    name: "Zeus",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jjeus.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 252,
    type: "SL",
    category: "slot",
  },
  {
    name: "All Star Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jallstarfishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 119,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Bombing Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbombingishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 20,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Boom Legend",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jboomlegend.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 71,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Dinosaur Tycoon",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdinosaurtycoon.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 42,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Dinosaur Tycoon II",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdinosaurtycoon2.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 212,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Dragon Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jdragonfortune.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 60,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Happy Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jhappyfishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 82,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Jackpot Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jjackpotfishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 32,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Mega Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jmegofishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 74,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Ocean King Jackpot",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Joceankingjackpot.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 289,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Royal Fishing",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jroyalfishing.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 1,
    type: "FISH",
    category: "fish",
  },
  {
    name: "Bingo Carnaval",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jbingocarnaval.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 148,
    type: "CB",
    category: "card",
  },
  {
    name: "Color Game",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jcolorgame.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 197,
    type: "CB",
    category: "card",
  },
  {
    name: "Blackjack",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jblackjack.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 219,
    type: "CB",
    category: "card",
  },
  {
    name: "7up7down",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/J7up7down.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 124,
    type: "CB",
    category: "card",
  },
  {
    name: "AK47",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jteenpatiiak47.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 75,
    type: "CB",
    category: "card",
  },
  {
    name: "Andar Bahar",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Janderbahar.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 79,
    type: "CB",
    category: "card",
  },
  {
    name: "Baccarat",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jbaccarat.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 152,
    type: "CB",
    category: "card",
  },
  {
    name: "Bingo Adventure",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jbingoadventure.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 177,
    type: "CB",
    category: "card",
  },
  {
    name: "Blackjack Lucky Ladies",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jblackjackluckyladies.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 220,
    type: "CB",
    category: "card",
  },
  {
    name: "Calaca Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jcalacabingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 149,
    type: "CB",
    category: "card",
  },
  {
    name: "Callbreak",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jcallbreak.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 127,
    type: "CB",
    category: "card",
  },
  {
    name: "Callbreak Quick",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jcallbreakquick.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 160,
    type: "CB",
    category: "card",
  },
  {
    name: "Candyland Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jcandylandbingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 216,
    type: "CB",
    category: "card",
  },
  {
    name: "Color Prediction",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jcolorprediction.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 204,
    type: "CB",
    category: "card",
  },
  {
    name: "Dragon & Tiger",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jdragon&tiger.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 123,
    type: "CB",
    category: "card",
  },
  {
    name: "Fish Prawn Crab",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jfishprawncrab.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 389,
    type: "CB",
    category: "card",
  },
  {
    name: "Fortune Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jfortunebingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 139,
    type: "CB",
    category: "card",
  },
  {
    name: "Go Goal Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jgogoalbingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 203,
    type: "CB",
    category: "card",
  },
  {
    name: "Jackpot Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jjackpotbingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 154,
    type: "CB",
    category: "card",
  },
  {
    name: "Jogo do Bicho",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jjogodobicho.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 297,
    type: "CB",
    category: "card",
  },
  {
    name: "Lucky Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jluckybingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 184,
    type: "CB",
    category: "card",
  },
  {
    name: "Ludo Quick",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jludoquick.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 163,
    type: "CB",
    category: "card",
  },
  {
    name: "Magic Lamp Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jmagiclampbingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 217,
    type: "CB",
    category: "card",
  },
  {
    name: "Mini Flush",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jminiflush.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 120,
    type: "CB",
    category: "card",
  },
  {
    name: "Number King",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jnumberking.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 111,
    type: "CB",
    category: "card",
  },
  {
    name: "Pusoy Go",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jpusygo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 211,
    type: "CB",
    category: "card",
  },
  {
    name: "Rummy",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jrummy.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 94,
    type: "CB",
    category: "card",
  },
  {
    name: "Speed Baccarat",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jspeedbaccarat.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 262,
    type: "CB",
    category: "card",
  },
  {
    name: "Super Bingo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jsuperbingo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 151,
    type: "CB",
    category: "card",
  },
  {
    name: "TeenPatti",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jteenpatti.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 72,
    type: "CB",
    category: "card",
  },
  {
    name: "TeenPatti 20-20",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jteenpatti20-20.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 161,
    type: "CB",
    category: "card",
  },
  {
    name: "Tongits Go",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogostable/Jtongitsgo.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 199,
    type: "CB",
    category: "card",
  },
  {
    name: "Fortune Garuda 500",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunegaruda500.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 696,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gems 500",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/Jgamelogo/Jfortunegems500.png",
    provider_code: "JE",
    provider: "jili",
    game_id: 540,
    type: "SL",
    category: "slot",
  },
];
