export const PG_GAMES = [
  {
    name: "Bakery Bonanza",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGbakerybananz.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1418544,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bali Vacation",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGbailvacation.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 94,
    type: "SL",
    category: "slot",
  },
  {
    name: "Anubis Wrath",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGaunbiswrath.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1623475,
    type: "SL",
    category: "slot",
  },
  {
    name: "Asgardian Rising",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGasgardianrising.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1340277,
    type: "SL",
    category: "slot",
  },
  {
    name: "Alchemy Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGalchemygold.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1368367,
    type: "SL",
    category: "slot",
  },
  {
    name: "Candy Bonanza",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcandysuperwin.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 100,
    type: "SL",
    category: "slot",
  },
  {
    name: "Candy Burst",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcandyburst.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 70,
    type: "SL",
    category: "slot",
  },
  {
    name: "Caishen Wins",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcaishenwins.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 71,
    type: "SL",
    category: "slot",
  },
  {
    name: "Butterfly Blossom",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGbutterflyblossom.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 125,
    type: "SL",
    category: "slot",
  },
  {
    name: "Buffalo Win",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGbuffalowin.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 108,
    type: "SL",
    category: "slot",
  },
  {
    name: "Bikini Paradise",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGbikiniparadise.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 69,
    type: "SL",
    category: "slot",
  },
  {
    name: "Battleground Royale",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGbattlegroundroyale.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 124,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Hatch",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdragonhatch.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 57,
    type: "SL",
    category: "slot",
  },
  {
    name: "Diner Frenzy Spins",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdinrtgtrnxtdpind.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1935269,
    type: "SL",
    category: "slot",
  },
  {
    name: "Double Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdoublefortune.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 48,
    type: "SL",
    category: "slot",
  },
  {
    name: "Diner Delights",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdinerdelights.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1372643,
    type: "SL",
    category: "slot",
  },
  {
    name: "Destiny of Sun & Moon",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdestinyofsunandmoon.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 121,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dead Man's Riches",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdeadmansriches.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1865521,
    type: "SL",
    category: "slot",
  },
  {
    name: "Crypto Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcryptogold.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 103,
    type: "SL",
    category: "slot",
  },
  {
    name: "Cruise Royale",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcruiseroyale.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1473388,
    type: "SL",
    category: "slot",
  },
  {
    name: "Cocktail Nights",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcocktailnights.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 117,
    type: "SL",
    category: "slot",
  },
  {
    name: "Circus Delight",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcircusdelight.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 80,
    type: "SL",
    category: "slot",
  },
  {
    name: "Chocolate Deluxe",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGchocolatedeludx.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1666445,
    type: "SL",
    category: "slot",
  },
  {
    name: "Chicky Run",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGchockyrun.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1738001,
    type: "GM",
    category: "gamble",
  },
  {
    name: "Cash Mania",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcashmania.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1682240,
    type: "SL",
    category: "slot",
  },
  {
    name: "Captain's Bounty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGcaptainscounty.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 54,
    type: "SL",
    category: "slot",
  },
  {
    name: "Emoji Riches",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGemojriches.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 114,
    type: "SL",
    category: "slot",
  },
  {
    name: "Egypt's Book of Mystery",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGegyptsbookofmystery.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 73,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dreams of Macau",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdreamsofmacau.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 79,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Tiger Luck",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdragontigerluck.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 63,
    type: "SL",
    category: "slot",
  },
  {
    name: "Treasures of Aztec",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdragonstreasurequest.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 87,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Legend",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdragonlegend.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 29,
    type: "SL",
    category: "slot",
  },
  {
    name: "Dragon Hatch 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGdragonhatch2.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1451122,
    type: "SL",
    category: "slot",
  },
  {
    name: "Emperor's Favour",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGemperorsfavour.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 44,
    type: "SL",
    category: "slot",
  },
  {
    name: "Werewolf's Hunt",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGerewolfshunt.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1615454,
    type: "SL",
    category: "slot",
  },
  {
    name: "Flirting Scholar",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGflirtingcholar.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 61,
    type: "SL",
    category: "slot",
  },
  {
    name: "Forge of Wealth",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGforgeofwealth.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1555350,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Gods",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfortunegods.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 3,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Mouse",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfortunemouse.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 68,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Ox",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfortuneox.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 98,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Rabbit",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfortunerabbit.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1543462,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Snake",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfortunesnake.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1879752,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Tiger",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfortunetiger.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 126,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fortune Dragon",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfrotunedragon.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1695365,
    type: "SL",
    category: "slot",
  },
  {
    name: "Fruity Candy",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfruitycandy.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1397455,
    type: "SL",
    category: "slot",
  },
  {
    name: "Futebol Fever",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGfutebol.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1778752,
    type: "SL",
    category: "slot",
  },
  {
    name: "Galactic Gems",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgalacticgems.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 86,
    type: "SL",
    category: "slot",
  },
  {
    name: "Gemstones Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgalaxyminer.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1671262,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ganesha Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGganeshagold.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 42,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ganesha Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGganeshagortune.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 75,
    type: "SL",
    category: "slot",
  },
  {
    name: "Garuda Gems",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgarudagems.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 122,
    type: "SL",
    category: "slot",
  },
  {
    name: "Geisha's Revenge",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgeishasrevenge.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1702123,
    type: "SL",
    category: "slot",
  },
  {
    name: "Gem Saviour",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgemsaviour.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 2,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Clover Riches",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGluckycloverriches.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1601012,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Neko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGluckyneko.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 89,
    type: "SL",
    category: "slot",
  },
  {
    name: "Lucky Piggy",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGluckypiggy.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 130,
    type: "SL",
    category: "slot",
  },
  {
    name: "Medusa",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmadusa.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 7,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mafia Mayhem",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmafaimayhem.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1580541,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mahjong Ways",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmahjongways.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 65,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mahjong Ways 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmahjongways2.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 74,
    type: "SL",
    category: "slot",
  },
  {
    name: "Majestic Treasures",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmajestictreasures.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 95,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mask Carnival",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmaskcarnival.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 118,
    type: "SL",
    category: "slot",
  },
  {
    name: "Medusa II",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmedusa2.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 6,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mermaid Riches",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmermaidriches.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 102,
    type: "SL",
    category: "slot",
  },
  {
    name: "Midas Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmidasfortune.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1402846,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mr. Hallow-Win",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmrhallowwin.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 35,
    type: "SL",
    category: "slot",
  },
  {
    name: "Muay Thai Champion",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmuaythaichmpion.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 64,
    type: "SL",
    category: "slot",
  },
  {
    name: "Museum Mystery",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmuseummystery.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1755623,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mystical Spirits",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmysticalspririts.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1432733,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mystic Potion",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmysticpotions.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1717688,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ninja Racoon Frenzy",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGninjaracconfrenzy.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1529867,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ninja vs Samurai",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGninjavssamurai.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 59,
    type: "SL",
    category: "slot",
  },
  {
    name: "Oishi Delights",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGoishidelights.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1815268,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jack Frost's Winter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGjackfrostswinter.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 97,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jack the Giant Hunter",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGjackthegainthunter.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1834850,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jewels of Prosperity",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGjewelsofprosperity.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 88,
    type: "SL",
    category: "slot",
  },
  {
    name: "Journey to the Wealth",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGjourneytothewealth.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 50,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jungle Delight",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGjungledelight.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 40,
    type: "SL",
    category: "slot",
  },
  {
    name: "Jurassic Kingdom",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGjurassickingdom.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 110,
    type: "SL",
    category: "slot",
  },
  {
    name: "Knockout Riches",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGknockoutriches.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1881268,
    type: "SL",
    category: "slot",
  },
  {
    name: "Safari Wilds",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGsafariwilds.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1594259,
    type: "SL",
    category: "slot",
  },
  {
    name: "Santa's Gift Rush",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGsantasgiftrush.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 37,
    type: "SL",
    category: "slot",
  },
  {
    name: "Secrets of Cleopatra",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGsecretsofcleopatra.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 90,
    type: "SL",
    category: "slot",
  },
  {
    name: "Shaolin Soccer",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGshaolinsoccer.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 67,
    type: "SL",
    category: "slot",
  },
  {
    name: "Shark Bounty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGsharkbounty.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1648578,
    type: "SL",
    category: "slot",
  },
  {
    name: "Songkran Splash",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGsongkransplash.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1448762,
    type: "SL",
    category: "slot",
  },
  {
    name: "Speed Winner",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGspeedwinner.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 127,
    type: "SL",
    category: "slot",
  },
  {
    name: "Spirited Wonders",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGspiritedwonders.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 119,
    type: "SL",
    category: "slot",
  },
  {
    name: "Supermarket Spree",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGsuermarketspree.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 115,
    type: "SL",
    category: "slot",
  },
  {
    name: "Super Golf Drive",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGsupergolfdrive.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1513328,
    type: "SL",
    category: "slot",
  },
  {
    name: "Symbols of Egypt",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGsymbolsofegypt.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 41,
    type: "SL",
    category: "slot",
  },
  {
    name: "Thai River Wonders",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGthairiverwonders.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 92,
    type: "SL",
    category: "slot",
  },
  {
    name: "The Great Icescape",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGthegrateicescape.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 53,
    type: "SL",
    category: "slot",
  },
  {
    name: "The Queen's Banquet",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGthequeensbanquet.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 120,
    type: "SL",
    category: "slot",
  },
  {
    name: "Three Crazy Piggies",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGthreecrazypiggies.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1727711,
    type: "SL",
    category: "slot",
  },
  {
    name: "Galaxy Miner",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgalaxyminer.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1471011,
    type: "SL",
    category: "slot",
  },
  {
    name: "Gem Saviour Conquest",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgemsaviourconquest.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 62,
    type: "SL",
    category: "slot",
  },
  {
    name: "Gem Saviour Sword",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgemsavioursword.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 38,
    type: "SL",
    category: "slot",
  },
  {
    name: "Genie's 3 Wishes",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgenies3wishes.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 85,
    type: "SL",
    category: "slot",
  },
  {
    name: "Gladiator's Glory",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgladiatorsglory.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1572362,
    type: "SL",
    category: "slot",
  },
  {
    name: "Grimy's Bounty Hansel & Gretel",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgrimmysbonutyhansel&gretel.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 68,
    type: "SL",
    category: "slot",
  },
  {
    name: "Guardians of Ice and Fire",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGguardiansoficeandfire.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 91,
    type: "SL",
    category: "slot",
  },
  {
    name: "Queen of Bounty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGgueenofbonuty.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 84,
    type: "SL",
    category: "slot",
  },
  {
    name: "Hawaiian Tiki",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGhawallantiki.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1381200,
    type: "SL",
    category: "slot",
  },
  {
    name: "Heist Stakes",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGheiststackes.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 105,
    type: "SL",
    category: "slot",
  },
  {
    name: "Hip Hop Panda",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGhiphoppanda.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 33,
    type: "SL",
    category: "slot",
  },
  {
    name: "Hood vs Wolf",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGhoodvswolf.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 18,
    type: "SL",
    category: "slot",
  },
  {
    name: "Honey Trap of Diao Chan",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGhooneytrapofdiaochan.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1,
    type: "SL",
    category: "slot",
  },
  {
    name: "Medusa 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmedusa2.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 95,
    type: "SL",
    category: "slot",
  },
  {
    name: "Mystic Potions",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGmysticpotions.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 207,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ninja Raccoon Frenzy",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGninjaracconfrenzy.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1529867,
    type: "SL",
    category: "slot",
  },
  {
    name: "Opera Dynasty",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGoperadynasty.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 51,
    type: "SL",
    category: "slot",
  },
  {
    name: "Oriental Prosperity",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGorientalprosperity.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 113,
    type: "SL",
    category: "slot",
  },
  {
    name: "Phoenix Rises",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGphoenixrises.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 75,
    type: "SL",
    category: "slot",
  },
  {
    name: "Piggy Gold",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGpiggygold.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 39,
    type: "SL",
    category: "slot",
  },
  {
    name: "Pinata Wins",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGpinatawins.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 102,
    type: "SL",
    category: "slot",
  },
  {
    name: "Plushie Frenzy",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGplushieprenzy.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1208882,
    type: "SL",
    category: "slot",
  },
  {
    name: "Prosperity Lion",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGprosperitylion.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 107,
    type: "SL",
    category: "slot",
  },
  {
    name: "Prosperity Fortune Tree",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGprosprerityforutnetree.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1260175,
    type: "SL",
    category: "slot",
  },
  {
    name: "Raider Jane's Crypt of Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGraiderjanescryptofrotune.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 106,
    type: "SL",
    category: "slot",
  },
  {
    name: "Rave Party Fever",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGravepartyfever.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 118,
    type: "SL",
    category: "slot",
  },
  {
    name: "Reel Love",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGreellove.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 25,
    type: "SL",
    category: "slot",
  },
  {
    name: "Rio Fantasia",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGriofantasia.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1786529,
    type: "SL",
    category: "slot",
  },
  {
    name: "Rise of Apollo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGriseofapollo.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 101,
    type: "SL",
    category: "slot",
  },
  {
    name: "Rooster Rumble",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGroosterrumble.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1572362,
    type: "SL",
    category: "slot",
  },
  {
    name: "Totem Wonders",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGtotemwonders.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 46,
    type: "SL",
    category: "slot",
  },
  {
    name: "Tree of Fortune",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGtreeoffortune.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 82,
    type: "SL",
    category: "slot",
  },
  {
    name: "Ultimate Striker",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGultimatestriker.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1815268,
    type: "SL",
    category: "slot",
  },
  {
    name: "Vampire's Charm",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGvampirescharm.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 58,
    type: "SL",
    category: "slot",
  },
  {
    name: "Way of the Qilin",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwayoftheqilin.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 51,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Ape",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwildape.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 104,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Bandito",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwildbandito.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 135,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Bounty Showdown",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwildbountyshowdon.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1918388,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Coaster",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwildcoaster.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 132,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Fireworks",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwildfireworks.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 83,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wild Heist Cashout",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwildheistcashout.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1878274,
    type: "SL",
    category: "slot",
  },
  {
    name: "Wings of Iguazu",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwingsoflguazu.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 181,
    type: "SL",
    category: "slot",
  },
  {
    name: "Win Win Fish Prawn Crab",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwinwinfishprawncarb.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 31,
    type: "SL",
    category: "slot",
  },
  {
    name: "Win Win Won",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGwinwinwon.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 24,
    type: "SL",
    category: "slot",
  },
  {
    name: "Yakuza Honor",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGyakuzahonor.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1601012,
    type: "SL",
    category: "slot",
  },
  {
    name: "Zombie Outbreak",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/PGgamelogo/PGzombieoutbreak.jpg",
    provider_code: "PG",
    provider: "pg",
    game_id: 1368367,
    type: "SL",
    category: "slot",
  },
];
