export const TU_GAMES = [
  {
    name: "Vortex 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/06-vortex2-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortex2",
    type: "SL",
    category: "slot",
  },
  {
    name: "Vortex Halloween",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOvortexhalloween.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortexhalloween",
    type: "SL",
    category: "slot",
  },
  {
    name: "Vortex Powerplay",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/gamelogo/07-vortexpowerplay-Thumb-logo%20-%201x1.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortexpowerplay",
    type: "SL",
    category: "slot",
  },
  {
    name: "Chicken Route",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOchickenroute.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "chickenroute",
    type: "MG",
    category: "casino",
  },
  {
    name: "Limbo Rider",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOlimborider.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "limbo",
    type: "MG",
    category: "casino",
  },
  {
    name: "Mysteco",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOmysteco.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "mysteco",
    type: "MG",
    category: "casino",
  },
  {
    name: "Vortex",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOvortex.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortex",
    type: "SL",
    category: "casino",
  },
  {
    name: "Turbo Plinko",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOturboplinko.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "turboplinko",
    type: "MG",
    category: "casino",
  },
  {
    name: "1Tap Mines",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBO1tapmines.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "1tapmines",
    type: "MG",
    category: "casino",
  },
  {
    name: "Aero",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOaero.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "aero",
    type: "MG",
    category: "casino",
  },
  {
    name: "Ball & Ball",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOball&ball.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "ballandball",
    type: "SL",
    category: "slot",
  },
  {
    name: "Catanza",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBObonuscatanz.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "catanza",
    type: "SL",
    category: "slot",
  },
  {
    name: "Book of Mines",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBObookofmine.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "bookofmines",
    type: "MG",
    category: "casino",
  },
  {
    name: "Bubbles",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBObubbles.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "bubbles",
    type: "MG",
    category: "casino",
  },
  {
    name: "CrashX Football Edition",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOcarshxfootball.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "crashfootball",
    type: "MG",
    category: "casino",
  },
  {
    name: "CrashX",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOcrashx.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "crash",
    type: "MG",
    category: "casino",
  },
  {
    name: "Crystal Poker",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOcrystalpoker.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "crystalpoker",
    type: "SL",
    category: "slot",
  },
  {
    name: "Dice Twice",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOdicetwice.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "dice",
    type: "MG",
    category: "casino",
  },
  {
    name: "Donny King",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOdonnyking.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "donnyking",
    type: "MG",
    category: "casino",
  },
  {
    name: "Balloon Doggo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOdoogoballoon.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "balloondoggo",
    type: "MG",
    category: "casino",
  },
  {
    name: "Double Roll",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOdoubleroll.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "double",
    type: "MG",
    category: "casino",
  },
  {
    name: "Fast Fielder",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOfastfielder.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "fastfielder",
    type: "MG",
    category: "casino",
  },
  {
    name: "Fruit Towers",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOfruittowers.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "fruittowers",
    type: "MG",
    category: "casino",
  },
  {
    name: "Fury Stairs",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOfurystairs.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "stairs",
    type: "MG",
    category: "casino",
  },
  {
    name: "Hamsta",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOhamsta.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "hamsta",
    type: "MG",
    category: "casino",
  },
  {
    name: "HiLo",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOhilo.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "hilo",
    type: "CB",
    category: "casino",
  },
  {
    name: "Jewel Clicker",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOjewelchicker.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "jewelclicker",
    type: "MG",
    category: "casino",
  },
  {
    name: "Mines",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOmines.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "mines",
    type: "MG",
    category: "casino",
  },
  {
    name: "Pumped X",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOpumped.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "pumpedx",
    type: "MG",
    category: "casino",
  },
  {
    name: "Rings of Olympus",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOringsofolympus.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "ringsofolympus",
    type: "SL",
    category: "slot",
  },
  {
    name: "Spin Strike",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOspinstrike.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "spinstrike",
    type: "MG",
    category: "casino",
  },
  {
    name: "Tapinata",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOtapinsta.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "tapinata",
    type: "MG",
    category: "casino",
  },
  {
    name: "Towers",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOtowers.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "towers",
    type: "MG",
    category: "casino",
  },
  {
    name: "Turbo Mines",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOturbomines.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "turbomines",
    type: "MG",
    category: "casino",
  },
  {
    name: "Vortex 2",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOvortex2.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortex2",
    type: "SL",
    category: "slot",
  },
  {
    name: "Vortex Safari",
    logo: "https://utprqkqiqjtjtzksjrng.supabase.co/storage/v1/object/public/TURBOgamelogo/TURBOvortexsafari.png",
    provider_code: "TU",
    provider: "turbo",
    game_id: "vortexsafari",
    type: "SL",
    category: "slot",
  },
];
